/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrderItemStatus = "cancelled" | "new" | "preparing" | "ready" | "sent" | "served";

export type OrderStatus = "billed" | "cancelled" | "merged" | "open" | "paid" | "partially_served" | "sent_to_kitchen" | "served" | "void";

export type OrderType = "delivery" | "dine_in" | "takeaway";

export type PaymentScope = "full" | "item" | "partial";

export type PaymentType = "card" | "cash" | "transfer";

export type PrintJobStatus = "cancelled" | "failed" | "printing" | "queued" | "retry" | "success";

export type TakeawayStage = "delivered" | "out_for_delivery" | "preparing";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "cashier" | "kitchen" | "waiter";

export interface Agents {
  /**
   * API key bcrypt hash (cost 12). Düz key sadece register response'unda bir kez döner; DB'de tutulmaz.
   */
  api_key_hash: string;
  /**
   * Kayıt zamanı (register endpoint). Audit + onboarding analitiği.
   */
  created_at: Generated<Timestamp>;
  /**
   * Cihaz parmak izi (machine-id + os + hostname türev hash). (tenant_id, device_fingerprint) UNIQUE — aynı cihaz çoklu register engellenir.
   */
  device_fingerprint: string;
  /**
   * UUIDv7 (application-generated). Time-ordered insert locality için v7 tercih edildi.
   */
  id: string;
  /**
   * Son heartbeat/auth zamanı (nullable — henüz aktivite yoksa NULL). Admin UI Phase 4+ "son görülme" sıralaması.
   */
  last_seen_at: Timestamp | null;
  /**
   * Revoke nedeni serbest metin (manuel admin notu veya otomatik kural çıktısı). NULL iken aktif.
   */
  revoke_reason: string | null;
  /**
   * Revoke zamanı (nullable). NULL = aktif. Set edildiğinde auth reddedilir; kayıt audit için silinmez.
   */
  revoked_at: Timestamp | null;
  /**
   * Tenant FK. ON DELETE CASCADE — tenant silinince agent kayıtları otomatik temizlenir (multi-tenant izolasyon hijyeni).
   */
  tenant_id: string;
}

export interface Areas {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AttributeGroups {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_required: Generated<boolean>;
  name: string;
  selection_type: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AttributeOptions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  extra_price_cents: Generated<number>;
  group_id: string;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditLogs {
  actor: Generated<Json>;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_type: string;
  id: string;
  payload: Generated<Json>;
  tenant_id: string | null;
}

export interface CallLogs {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: string;
  normalized_phone: string;
  opened_order_id: string | null;
  raw_phone: string | null;
  received_at: Generated<Timestamp>;
  station_user_id: string | null;
  status: string;
  tenant_id: string;
}

export interface Categories {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  icon: Generated<string>;
  id: string;
  /**
   * ADR-020 K2: TRUE ise bu kategori altındaki sipariş kalemleri KDS'e düşer + mutfak ticket print'i tetikler. Default TRUE (mevcut yemek kategorileri); içecek vb. bar/kasa hattı için admin sonradan FALSE yapar.
   */
  kitchen_print: Generated<boolean>;
  name: string;
  /**
   * ADR-032 Amd1: bu kategorinin mutfak fişini hangi istasyon yazıcısının basacağı. NULL = taban istasyon (kitchen). Geçerli değerler shared-types KITCHEN_STATION_KINDS alt kümesi (kitchen | grill); doğrulama enqueue'da, DB CHECK yok. kitchen_print bayrağından ORTOGONAL: o "mutfağa gider mi", bu "hangi yazıcı" sorusunu yanıtlar.
   */
  print_station: string | null;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CategoryAttributeGroups {
  category_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface CustomerAddresses {
  address_line: string;
  address_note: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  district: string | null;
  id: string;
  is_default: Generated<boolean>;
  is_deleted: Generated<boolean>;
  neighborhood: string | null;
  tenant_id: string;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerPhones {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: string;
  is_mobile: Generated<boolean>;
  is_primary: Generated<boolean>;
  normalized_phone: string;
  raw_phone: Generated<string>;
  tenant_id: string;
}

export interface Customers {
  blacklist_reason: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  full_name: string;
  id: string;
  is_blacklisted: Generated<boolean>;
  last_order_at: Timestamp | null;
  legacy_v3_no: Int8 | null;
  note: string | null;
  tenant_id: string;
  total_orders: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface OrderItemAttributes {
  attribute_group_id: string;
  attribute_option_id: string;
  created_at: Generated<Timestamp>;
  extra_price_cents_snapshot: number;
  group_name_snapshot: string;
  id: string;
  option_name_snapshot: string;
  order_item_id: string;
  tenant_id: string;
}

export interface OrderItemBatches {
  /**
   * ADR-013 Amd1: per-attempt idempotency token for one add-items request. NOT NULL — a row exists only for a key-bearing request; legacy keyless clients bypass this table entirely (items inserted directly = pre-Amendment behaviour).
   */
  batch_key: string;
  created_at: Generated<Timestamp>;
  /**
   * ADR-013 Amd1: actor who created the batch (users.id). FK ON DELETE SET NULL — user hard-delete nulls the actor but keeps the marker. Deliberately NOT in an all-or-none CHECK (soft-void actor-FK lesson: 23503/23514 avoidance).
   */
  created_by_user_id: string | null;
  id: string;
  order_id: string;
  tenant_id: string;
}

export interface OrderItems {
  category_name_snapshot: string;
  created_at: Generated<Timestamp>;
  created_by_name: string | null;
  created_by_user_id: string | null;
  id: string;
  is_comped: Generated<boolean>;
  note: string | null;
  order_id: string;
  product_id: string | null;
  product_name: string;
  quantity: Generated<number>;
  status: Generated<OrderItemStatus>;
  tenant_id: string;
  total_cents: number;
  unit_price_cents: number;
  updated_at: Generated<Timestamp>;
  variant_id_snapshot: string | null;
  variant_name_snapshot: string | null;
  variant_price_delta_cents_snapshot: number | null;
}

export interface OrderNoCounters {
  business_date: Timestamp;
  last_no: Generated<number>;
  tenant_id: string;
}

export interface Orders {
  /**
   * Sipariş alındığı andaki areas.name snapshot. Bölge hard delete edilince table.area_id NULL, rapor query snapshot'tan okur.
   */
  area_name_snapshot: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  delivery_address_snapshot: string | null;
  delivery_note: string | null;
  id: string;
  /**
   * ADR-013 Amd1: per-attempt idempotency token for POST /orders (create). NULL = legacy client (no guard, pre-Amendment behaviour). Partial UNIQUE (tenant_id, idempotency_key) WHERE NOT NULL collapses a retried create into a 200 replay instead of a duplicate order or an ambiguous 409.
   */
  idempotency_key: string | null;
  is_fully_comped: Generated<boolean>;
  /**
   * ADR-029: kaynak sipariş başka adisyona birleştirilince (status=merged) hedef sipariş id. Forensic iz + idempotency. NULL = birleştirilmemiş.
   */
  merged_into_order_id: string | null;
  note: string | null;
  order_no: number;
  order_type: Generated<OrderType>;
  planned_payment_type: PaymentType | null;
  status: Generated<OrderStatus>;
  store_date: Timestamp;
  /**
   * Sipariş alındığı andaki tables.code snapshot (ADR-003 §7). Masa hard delete edilince table_id NULL olur ama snapshot kalır → rapor doğru.
   */
  table_code_snapshot: string | null;
  table_id: string | null;
  takeaway_stage: TakeawayStage | null;
  tenant_id: string;
  total_cents: Generated<number>;
  updated_at: Generated<Timestamp>;
  waiter_user_id: string | null;
}

export interface PaymentItems {
  line_total_cents: number;
  order_item_id: string;
  payer_label: string | null;
  payer_no: number | null;
  payment_id: string;
  quantity: number;
  tenant_id: string;
  unit_price_cents_snapshot: number;
}

export interface Payments {
  amount_cents: number;
  cash_received_cents: number | null;
  change_amount_cents: number | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  id: string;
  idempotency_key: string;
  note: string | null;
  order_id: string;
  payer_label: string | null;
  payer_no: number | null;
  payment_scope: PaymentScope;
  payment_type: PaymentType;
  tenant_id: string;
  tip_amount_cents: number | null;
  /**
   * ADR-033 K6: zorunlu void sebebi (enum). wrong_payment_type|wrong_amount|wrong_table|duplicate|other. Serbest metin YOK (PII önlemi).
   */
  void_reason_code: string | null;
  /**
   * ADR-033: ödeme void anı (UTC). NULL = aktif; NOT NULL = geçersiz (aynı-gün geri alındı). Tüm aritmetik SUM(amount_cents) siteleri voided_at IS NULL ile dışlar.
   */
  voided_at: Timestamp | null;
  /**
   * ADR-033: void aktörü (users.id). FK ON DELETE SET NULL — kullanıcı hard-delete edilince NULL'a düşer (void kaydı voided_at+reason ile KALIR). all-or-none CHECK'e DAHİL DEĞİL. Forensic aktör izi audit_logs.actor_user_id'de.
   */
  voided_by_user_id: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PrintJobs {
  /**
   * ADR-004 Amendment 1: print job deneme sayacı. printing→failed transition'ında +1; queued→printing ve printing→success değişmez. CHECK 0..100 (sonsuz retry guard).
   */
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  payload: Generated<Json>;
  /**
   * ADR-004 Amendment 3: retry backoff zamanı. printing→retry transition'ında now()+10s*2^(attempts-1); claim sorgusu retry_at<=now() olunca job'u yeniden printing alır (lazy requeue). queued ve terminal (success/cancelled) durumda NULL.
   */
  retry_at: Timestamp | null;
  status: Generated<PrintJobStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProductAttributeGroups {
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  product_id: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface Products {
  barcode: string | null;
  category_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  is_active: Generated<boolean>;
  name: string;
  price_cents: number;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProductVariants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  price_delta_cents: number;
  product_id: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RefreshTokens {
  device_label: string | null;
  expires_at: Timestamp;
  family_id: string;
  id: string;
  ip_address: string | null;
  issued_at: Generated<Timestamp>;
  last_used_at: Timestamp | null;
  parent_id: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  tenant_id: string;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface Tables {
  area_id: string | null;
  capacity: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  /**
   * ADR-009 Amendment 2026-06-30 Karar A: kalıcı per-bölge masa görüntü numarası. Create/sync sırasında (bölge içinde) MAX+1 ile atanır, gap-preserving (silme/sync ile yeniden numaralanmaz). NULL = orphan/bölgesiz (area_id NULL) masa → etiket ham code'a düşer. tableLabel() util tek etiket kaynağıdır.
   */
  display_no: number | null;
  id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSettings {
  caller_id_bypass_patterns: Generated<string[]>;
  caller_id_station_user_id: string | null;
  created_at: Generated<Timestamp>;
  tenant_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: string;
  password_hash: string;
  role: UserRole;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  agents: Agents;
  areas: Areas;
  attribute_groups: AttributeGroups;
  attribute_options: AttributeOptions;
  audit_logs: AuditLogs;
  call_logs: CallLogs;
  categories: Categories;
  category_attribute_groups: CategoryAttributeGroups;
  customer_addresses: CustomerAddresses;
  customer_phones: CustomerPhones;
  customers: Customers;
  order_item_attributes: OrderItemAttributes;
  order_item_batches: OrderItemBatches;
  order_items: OrderItems;
  order_no_counters: OrderNoCounters;
  orders: Orders;
  payment_items: PaymentItems;
  payments: Payments;
  pgmigrations: Pgmigrations;
  print_jobs: PrintJobs;
  product_attribute_groups: ProductAttributeGroups;
  product_variants: ProductVariants;
  products: Products;
  refresh_tokens: RefreshTokens;
  tables: Tables;
  tenant_settings: TenantSettings;
  tenants: Tenants;
  users: Users;
}
