/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrderStatus = "cancelled" | "open" | "paid" | "sent_to_kitchen" | "served";

export type OrderType = "delivery" | "dine_in" | "takeaway";

export type PaymentScope = "equal_split" | "full_order" | "split_item";

export type PaymentType = "card" | "cash";

export type PrintJobStatus = "cancelled" | "failed" | "printing" | "queued" | "retry" | "success";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "cashier" | "kitchen" | "waiter";

export interface AuditLogs {
  actor: Generated<Json>;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_type: string;
  id: string;
  payload: Generated<Json>;
  tenant_id: string | null;
}

export interface CallLogs {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: string;
  normalized_phone: string;
  raw_phone: string | null;
  tenant_id: string;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CustomerPhones {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: string;
  normalized_phone: string;
  tenant_id: string;
}

export interface Customers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  full_name: string;
  id: string;
  note: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrderItems {
  category_name_snapshot: string;
  created_at: Generated<Timestamp>;
  id: string;
  is_comped: Generated<boolean>;
  note: string | null;
  order_id: string;
  product_id: string | null;
  product_name: string;
  quantity: Generated<number>;
  tenant_id: string;
  total_cents: number;
  unit_price_cents: number;
}

export interface OrderNoCounters {
  business_date: Timestamp;
  last_no: Generated<number>;
  tenant_id: string;
}

export interface Orders {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: string;
  is_fully_comped: Generated<boolean>;
  note: string | null;
  order_no: number;
  order_type: Generated<OrderType>;
  status: Generated<OrderStatus>;
  store_date: Timestamp;
  table_id: string | null;
  tenant_id: string;
  total_cents: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface PaymentItems {
  order_item_id: string;
  payment_id: string;
  tenant_id: string;
}

export interface Payments {
  amount_cents: number;
  created_at: Generated<Timestamp>;
  id: string;
  order_id: string;
  payment_scope: PaymentScope;
  payment_type: PaymentType;
  tenant_id: string;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PrintJobs {
  created_at: Generated<Timestamp>;
  id: string;
  payload: Generated<Json>;
  status: Generated<PrintJobStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Products {
  category_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  price_cents: number;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tables {
  capacity: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSettings {
  business_day_cutoff_hour: Generated<number>;
  created_at: Generated<Timestamp>;
  tenant_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  password_hash: string;
  role: UserRole;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  audit_logs: AuditLogs;
  call_logs: CallLogs;
  categories: Categories;
  customer_phones: CustomerPhones;
  customers: Customers;
  order_items: OrderItems;
  order_no_counters: OrderNoCounters;
  orders: Orders;
  payment_items: PaymentItems;
  payments: Payments;
  pgmigrations: Pgmigrations;
  print_jobs: PrintJobs;
  products: Products;
  tables: Tables;
  tenant_settings: TenantSettings;
  tenants: Tenants;
  users: Users;
}
