/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrderItemStatus = "cancelled" | "new" | "preparing" | "ready" | "sent" | "served";

export type OrderStatus = "billed" | "cancelled" | "open" | "paid" | "partially_served" | "sent_to_kitchen" | "served" | "void";

export type OrderType = "delivery" | "dine_in" | "takeaway";

export type PaymentScope = "full" | "item" | "partial";

export type PaymentType = "card" | "cash" | "transfer";

export type PrintJobStatus = "cancelled" | "failed" | "printing" | "queued" | "retry" | "success";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "cashier" | "kitchen" | "waiter";

export interface Areas {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AttributeGroups {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_required: Generated<boolean>;
  name: string;
  selection_type: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AttributeOptions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  extra_price_cents: Generated<number>;
  group_id: string;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface AuditLogs {
  actor: Generated<Json>;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_type: string;
  id: string;
  payload: Generated<Json>;
  tenant_id: string | null;
}

export interface CallLogs {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: string;
  normalized_phone: string;
  raw_phone: string | null;
  tenant_id: string;
}

export interface Categories {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  icon: Generated<string>;
  id: string;
  name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CategoryAttributeGroups {
  category_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface CustomerPhones {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: string;
  normalized_phone: string;
  tenant_id: string;
}

export interface Customers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  full_name: string;
  id: string;
  note: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrderItemAttributes {
  attribute_group_id: string;
  attribute_option_id: string;
  created_at: Generated<Timestamp>;
  extra_price_cents_snapshot: number;
  group_name_snapshot: string;
  id: string;
  option_name_snapshot: string;
  order_item_id: string;
  tenant_id: string;
}

export interface OrderItems {
  category_name_snapshot: string;
  created_at: Generated<Timestamp>;
  created_by_name: string | null;
  created_by_user_id: string | null;
  id: string;
  is_comped: Generated<boolean>;
  note: string | null;
  order_id: string;
  product_id: string | null;
  product_name: string;
  quantity: Generated<number>;
  status: Generated<OrderItemStatus>;
  tenant_id: string;
  total_cents: number;
  unit_price_cents: number;
}

export interface OrderNoCounters {
  business_date: Timestamp;
  last_no: Generated<number>;
  tenant_id: string;
}

export interface Orders {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  id: string;
  is_fully_comped: Generated<boolean>;
  note: string | null;
  order_no: number;
  order_type: Generated<OrderType>;
  status: Generated<OrderStatus>;
  store_date: Timestamp;
  table_id: string | null;
  tenant_id: string;
  total_cents: Generated<number>;
  updated_at: Generated<Timestamp>;
  waiter_user_id: string | null;
}

export interface PaymentItems {
  order_item_id: string;
  payment_id: string;
  tenant_id: string;
}

export interface Payments {
  amount_cents: number;
  created_at: Generated<Timestamp>;
  id: string;
  order_id: string;
  payment_scope: PaymentScope;
  payment_type: PaymentType;
  tenant_id: string;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PrintJobs {
  created_at: Generated<Timestamp>;
  id: string;
  payload: Generated<Json>;
  status: Generated<PrintJobStatus>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProductAttributeGroups {
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  product_id: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface Products {
  barcode: string | null;
  category_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  is_active: Generated<boolean>;
  name: string;
  price_cents: number;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProductVariants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  price_delta_cents: number;
  product_id: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RefreshTokens {
  device_label: string | null;
  expires_at: Timestamp;
  family_id: string;
  id: string;
  ip_address: string | null;
  issued_at: Generated<Timestamp>;
  last_used_at: Timestamp | null;
  parent_id: string | null;
  revoked_at: Timestamp | null;
  revoked_reason: string | null;
  tenant_id: string;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface Tables {
  area_id: string | null;
  capacity: number | null;
  code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSettings {
  business_day_cutoff_hour: Generated<number>;
  created_at: Generated<Timestamp>;
  tenant_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: string;
  password_hash: string;
  role: UserRole;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  areas: Areas;
  attribute_groups: AttributeGroups;
  attribute_options: AttributeOptions;
  audit_logs: AuditLogs;
  call_logs: CallLogs;
  categories: Categories;
  category_attribute_groups: CategoryAttributeGroups;
  customer_phones: CustomerPhones;
  customers: Customers;
  order_item_attributes: OrderItemAttributes;
  order_items: OrderItems;
  order_no_counters: OrderNoCounters;
  orders: Orders;
  payment_items: PaymentItems;
  payments: Payments;
  pgmigrations: Pgmigrations;
  print_jobs: PrintJobs;
  product_attribute_groups: ProductAttributeGroups;
  product_variants: ProductVariants;
  products: Products;
  refresh_tokens: RefreshTokens;
  tables: Tables;
  tenant_settings: TenantSettings;
  tenants: Tenants;
  users: Users;
}
