name: Setup Secrets (reusable)

on:
  workflow_call:
    secrets:
      MIGRATOR_DATABASE_URL:
        required: false
      APP_DATABASE_URL:
        required: false
      JWT_SECRET:
        required: false

jobs:
  mask:
    runs-on: ubuntu-latest
    steps:
      - name: Mask sensitive secrets
        run: |
          echo "::add-mask::${{ secrets.MIGRATOR_DATABASE_URL }}"
          echo "::add-mask::${{ secrets.APP_DATABASE_URL }}"
          echo "::add-mask::${{ secrets.JWT_SECRET }}"
